"""
Sigma DataTech Transaction Analytics Pipeline
AI-Generated by Module 1 | Day 7 — Pipeline Brain
Generated: 2026-05-26T08:57:35.998072+00:00

This file was produced by 1_spec_to_pipeline.py from a plain-English spec.
It is a FIRST DRAFT — review before running against production data.

Architecture: Bronze -> Silver -> Gold (medallion pattern)
"""

# ═══════════════════════════════════════════════════════════════
# SECTION 1: BRONZE + SILVER LAYERS
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, lit, coalesce, max as max_
from pyspark.sql.types import FloatType, StringType, DateType
import json
import os

def ingest_bronze(spark, input_path, output_path, run_date, run_id):
    # Read raw CSV files with all columns as strings
    transactions_df = (spark.read.option("header", "true")
                      .option("inferSchema", "false")
                       .csv(input_path))
    
    # Add metadata columns
    transactions_df = (transactions_df.withColumn("ingestion_timestamp", lit(run_date))
                      .withColumn("source_file", lit("transactions.csv"))
                       .withColumn("pipeline_run_id", lit(run_id)))
    
    # Write as Parquet partitioned by date
    transactions_df.write.partitionBy("ingestion_timestamp").parquet(output_path)

def transform_silver(spark, bronze_path, merchants_path, output_path, run_date):
    # Read Bronze Parquet with partition pruning on run_date
    transactions_df = (spark.read.parquet(bronze_path)
                      .where(col("ingestion_timestamp") == run_date))
    
    # Cast columns to correct types
    transactions_df = (transactions_df.withColumn("amount", col("amount").cast(FloatType()))
                       .withColumn("transaction_date", col("transaction_date").cast(DateType())))
    
    # Filter NULL transaction_id and negative amounts
    transactions_df = transactions_df.filter((col("transaction_id").isNotNull()) & (col("amount") >= 0))
    
    # Deduplicate on transaction_id keeping latest ingestion_timestamp
    deduped_df = (transactions_df.groupBy("transaction_id")
                 .agg(max_("ingestion_timestamp").alias("latest_timestamp")))
    transactions_df = transactions_df.join(deduped_df, on=["transaction_id", "ingestion_timestamp"], how="inner")
    
    # Read merchants data and cache it
    merchants_df = (spark.read.option("header", "true")
                    .option("inferSchema", "false")
                     .csv(merchants_path)
                    .withColumn("merchant_id", col("merchant_id").cast(StringType())))
    merchants_df = merchants_df.cache()
    
    # Enrich transactions with merchants data
    enriched_df = (transactions_df.join(broadcast(merchants_df), on="merchant_id", how="left_outer")
                  .withColumn("quality_flag", coalesce(col("merchant_name"), lit("UNMATCHED"))))
    
    # Write as Parquet partitioned by date
    enriched_df.write.partitionBy("transaction_date").parquet(output_path)

def main():
    # Initialize Spark session
    spark = (SparkSession.builder
            .appName("Sigma DataTech Transaction Analytics Pipeline")
             .getOrCreate())
    
    # Paths and run metadata
    input_path = "s3://sigma-datatech-raw/transactions.csv"
    merchants_path = "s3://sigma-datatech-raw/merchants.csv"
    bronze_path = "s3://sigma-datatech-bronze/"
    silver_path = "s3://sigma-datatech-silver/"
    run_date = "2026-05-27"
    run_id = "run-001"
    
    # Ingest bronze layer
    ingest_bronze(spark, input_path, f"{bronze_path}{run_date}", run_date, run_id)
    
    # Transform silver layer
    transform_silver(spark, f"{bronze_path}{run_date}", merchants_path, f"{silver_path}{run_date}", run_date)
    
    # Write run metadata summary to a JSON file
    metadata = {"run_date": run_date, "run_id": run_id, "status": "COMPLETED"}
    with open(f"s3://sigma-datatech-metadata/{run_id}.json", "w") as f:
        json.dump(metadata, f)

if __name__ == "__main__":
    main()


# ═══════════════════════════════════════════════════════════════
# SECTION 2: GOLD AGGREGATION LAYER
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, sum, count, max, broadcast, when, mode, coalesce, lit
from pyspark.sql.types import StructType, StructField, StringType, FloatType, DateType

def run_gold(spark, silver_path, gold_output_dir, run_date):
    # Build Gold tables
    build_merchant_performance(spark, silver_path, f"{gold_output_dir}/merchant_performance", run_date)
    build_customer_ltv(spark, silver_path, f"{gold_output_dir}/customer_ltv")
    build_daily_summary(spark, silver_path, f"{gold_output_dir}/daily_summary", run_date)

    # Write run metadata summary to JSON
    run_metadata = {
        "run_date": run_date,
        "status": "SUCCESS"
    }
    spark.read.text(spark.sparkContext.parallelize([str(run_metadata)])).write.json(f"{gold_output_dir}/run_metadata")

def build_merchant_performance(spark, silver_path, output_path, run_date):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path).where(col("date") == run_date)

    # Calculate metrics
    merchant_performance_df = silver_df.filter(col("status") == "COMPLETED") \
        .groupBy("merchant_id", "merchant_name", "category", "city", "date") \
       .agg(
            sum("amount").alias("total_revenue"),
            count("*").alias("txn_count"),
            (count(when(col("status") == "FAILED", 1)) / count("*") * 100).alias("failure_rate_pct")
        )

    # Write output
    merchant_performance_df.write.mode("overwrite").partitionBy("date").parquet(output_path)

def build_customer_ltv(spark, silver_path, output_path):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path).filter(col("status") == "COMPLETED")

    # Calculate metrics
    customer_ltv_df = silver_df.groupBy("customer_id") \
       .agg(
            sum("amount").alias("total_spent"),
            count("*").alias("total_txns"),
            avg("amount").alias("avg_txn_value"),
            min("transaction_date").alias("first_txn_date"),
            max("transaction_date").alias("last_txn_date"),
            coalesce(mode("payment_method").over(Window.partitionBy("customer_id")), lit(None)).alias("preferred_payment_method")
        )

    # Write output
    customer_ltv_df.write.mode("overwrite").parquet(output_path)

def build_daily_summary(spark, silver_path, output_path, run_date):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path).where(col("date") == run_date)

    # Calculate metrics
    daily_summary_df = silver_df.groupBy("date") \
        .agg(
            sum(when(col("status") == "COMPLETED", col("amount")).otherwise(lit(0))).alias("total_revenue"),
            count("*").alias("total_txns"),
            count(col("customer_id")).alias("unique_customers"),
            count(col("merchant_id")).alias("unique_merchants"),
            (count(when(col("status") == "FAILED", 1)) / count("*") * 100).alias("failure_rate_pct")
        )

    # Write output
    daily_summary_df.write.mode("overwrite").partitionBy("date").parquet(output_path)
