sigma_dbt:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: GEJKIOG-TKC55632
      user: student_genai
      private_key_path: /Users/as-mac-1358/Downloads/genai_training/day-6/sigma-genai-de/bonus/student_key.p8
      role: STUDENT_CORTEX
      database: SIGMA_DE
      warehouse: COMPUTE_WH
      schema: PUBLIC
      threads: 1
